language: R
cache: packages

# build matrix; turn on vdiffr only on r release
matrix:
  include:
  - r: release
  - r: 3.5
  - r: 3.4
  - r: 3.3
  - r: 3.2
    env: R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

