language: R
cache: packages

matrix:
  include:
  - os: linux
    dist: xenial
    before_install:
      - R -e 'install.packages("devtools")'
      - R -e 'devtools::install_github("Yashwants19/bh")'

  - os: osx
    osx_image: xcode9.4
      before_install:
        - R -e 'install.packages("devtools")'
        - R -e 'devtools::install_github("Yashwants19/bh")'
