/**
 * @file src/dbscan.cpp
 *
 * This is an autogenerated file containing implementations of C++ functions to
 * be called by the R dbscan binding.
 */
#include <rcpp_mlpack.h>
#define BINDING_TYPE BINDING_TYPE_R
#include <mlpack/methods/dbscan/dbscan_main.cpp>

// [[Rcpp::export]]
void dbscan_mlpackMain()
{
  mlpackMain();
}

// Any implementations of methods for dealing with model pointers will be put
// below this comment, if needed.


