/**
 * @file src/decision_stump.cpp
 *
 * This is an autogenerated file containing implementations of C functions to be
 * called by the R decision_stump binding.
 */
#include <rcpp_mlpack.h>
#define BINDING_TYPE BINDING_TYPE_R
#include <mlpack/methods/decision_stump/decision_stump_main.cpp>

// [[Rcpp::export]]
void decision_stump_mlpackMain()
{
  mlpackMain();
}

// Any implementations of methods for dealing with model pointers will be put
// below this comment, if needed.

// Get the pointer to a DSModel parameter.
// [[Rcpp::export]]
SEXP IO_GetParamDSModelPtr(const std::string& paramName)
{
  return std::move((Rcpp::XPtr<DSModel>) IO::GetParam<DSModel*>(paramName));
}

// Set the pointer to a DSModel parameter.
// [[Rcpp::export]]
void IO_SetParamDSModelPtr(const std::string& paramName, SEXP ptr)
{
  IO::GetParam<DSModel*>(paramName) =  Rcpp::as<Rcpp::XPtr<DSModel>>(ptr);
  IO::SetPassed(paramName);
}

// Serialize a DSModel pointer.
// [[Rcpp::export]]
Rcpp::RawVector SerializeDSModelPtr(SEXP ptr)
{
  std::ostringstream oss;
  {
    boost::archive::binary_oarchive oa(oss);
    oa << boost::serialization::make_nvp("DSModel",
          *Rcpp::as<Rcpp::XPtr<DSModel>>(ptr));
  }

  Rcpp::RawVector raw_vec(oss.str().size());

  // Copy the string buffer so we can return one that won't get deallocated when
  // we exit this function.
  memcpy(&raw_vec[0], oss.str().c_str(), oss.str().size());
  raw_vec.attr("type") = "DSModel";
  return raw_vec;
}

// Deserialize a DSModel pointer.
// [[Rcpp::export]]
SEXP DeserializeDSModelPtr(Rcpp::RawVector str)
{
  DSModel* ptr = new DSModel();

  std::istringstream iss(std::string((char *) &str[0], str.size()));
  {
    boost::archive::binary_iarchive ia(iss);
    ia >> boost::serialization::make_nvp("DSModel", *ptr);
  }

  // R will be responsible for freeing this.
  return std::move((Rcpp::XPtr<DSModel>)ptr);
}


