/**
 * @file src/det.cpp
 *
 * This is an autogenerated file containing implementations of C++ functions to
 * be called by the R det binding.
 */
#include <rcpp_mlpack.h>
#define BINDING_TYPE BINDING_TYPE_R
#include <mlpack/methods/det/det_main.cpp>

// [[Rcpp::export]]
void det_mlpackMain()
{
  mlpackMain();
}

// Any implementations of methods for dealing with model pointers will be put
// below this comment, if needed.

// Get the pointer to a DTree<> parameter.
// [[Rcpp::export]]
SEXP IO_GetParamDTreePtr(const std::string& paramName)
{
  return std::move((Rcpp::XPtr<DTree<>>) IO::GetParam<DTree<>*>(paramName));
}

// Set the pointer to a DTree<> parameter.
// [[Rcpp::export]]
void IO_SetParamDTreePtr(const std::string& paramName, SEXP ptr)
{
  IO::GetParam<DTree<>*>(paramName) =  Rcpp::as<Rcpp::XPtr<DTree<>>>(ptr);
  IO::SetPassed(paramName);
}

// Serialize a DTree<> pointer.
// [[Rcpp::export]]
Rcpp::RawVector SerializeDTreePtr(SEXP ptr)
{
  std::ostringstream oss;
  {
    cereal::BinaryOutputArchive oa(oss);
    oa << cereal::make_nvp("DTree",
          *Rcpp::as<Rcpp::XPtr<DTree<>>>(ptr));
  }

  Rcpp::RawVector raw_vec(oss.str().size());

  // Copy the string buffer so we can return one that won't get deallocated when
  // we exit this function.
  memcpy(&raw_vec[0], oss.str().c_str(), oss.str().size());
  raw_vec.attr("type") = "DTree";
  return raw_vec;
}

// Deserialize a DTree<> pointer.
// [[Rcpp::export]]
SEXP DeserializeDTreePtr(Rcpp::RawVector str)
{
  DTree<>* ptr = new DTree<>();

  std::istringstream iss(std::string((char *) &str[0], str.size()));
  {
    cereal::BinaryInputArchive ia(iss);
    ia >> cereal::make_nvp("DTree", *ptr);
  }

  // R will be responsible for freeing this.
  return std::move((Rcpp::XPtr<DTree<>>)ptr);
}


