/**
 * @file src/emst.cpp
 *
 * This is an autogenerated file containing implementations of C++ functions to
 * be called by the R emst binding.
 */
#include <rcpp_mlpack.h>
#define BINDING_TYPE BINDING_TYPE_R
#include <mlpack/methods/emst/emst_main.cpp>

// [[Rcpp::export]]
void emst_mlpackMain()
{
  mlpackMain();
}

// Any implementations of methods for dealing with model pointers will be put
// below this comment, if needed.


