/**
 * @file src/gmm_probability.cpp
 *
 * This is an autogenerated file containing implementations of C functions to be
 * called by the R gmm_probability binding.
 */
#include <rcpp_mlpack.h>
#define BINDING_TYPE BINDING_TYPE_R
#include <mlpack/methods/gmm/gmm_probability_main.cpp>

// [[Rcpp::export]]
void gmm_probability_mlpackMain()
{
  mlpackMain();
}

// Any implementations of methods for dealing with model pointers will be put
// below this comment, if needed.


