/**
 * @file src/hmm_generate.cpp
 *
 * This is an autogenerated file containing implementations of C++ functions to
 * be called by the R hmm_generate binding.
 */
#include <rcpp_mlpack.h>
#define BINDING_TYPE BINDING_TYPE_R
#include <mlpack/methods/hmm/hmm_generate_main.cpp>

// [[Rcpp::export]]
void hmm_generate_mlpackMain()
{
  mlpackMain();
}

// Any implementations of methods for dealing with model pointers will be put
// below this comment, if needed.

// Get the pointer to a HMMModel parameter.
// [[Rcpp::export]]
SEXP IO_GetParamHMMModelPtr(const std::string& paramName)
{
  return std::move((Rcpp::XPtr<HMMModel>) IO::GetParam<HMMModel*>(paramName));
}

// Set the pointer to a HMMModel parameter.
// [[Rcpp::export]]
void IO_SetParamHMMModelPtr(const std::string& paramName, SEXP ptr)
{
  IO::GetParam<HMMModel*>(paramName) =  Rcpp::as<Rcpp::XPtr<HMMModel>>(ptr);
  IO::SetPassed(paramName);
}

// Serialize a HMMModel pointer.
// [[Rcpp::export]]
Rcpp::RawVector SerializeHMMModelPtr(SEXP ptr)
{
  std::ostringstream oss;
  {
    cereal::BinaryOutputArchive oa(oss);
    oa << cereal::make_nvp("HMMModel",
          *Rcpp::as<Rcpp::XPtr<HMMModel>>(ptr));
  }

  Rcpp::RawVector raw_vec(oss.str().size());

  // Copy the string buffer so we can return one that won't get deallocated when
  // we exit this function.
  memcpy(&raw_vec[0], oss.str().c_str(), oss.str().size());
  raw_vec.attr("type") = "HMMModel";
  return raw_vec;
}

// Deserialize a HMMModel pointer.
// [[Rcpp::export]]
SEXP DeserializeHMMModelPtr(Rcpp::RawVector str)
{
  HMMModel* ptr = new HMMModel();

  std::istringstream iss(std::string((char *) &str[0], str.size()));
  {
    cereal::BinaryInputArchive ia(iss);
    ia >> cereal::make_nvp("HMMModel", *ptr);
  }

  // R will be responsible for freeing this.
  return std::move((Rcpp::XPtr<HMMModel>)ptr);
}


