/**
 * @file src/hmm_loglik.cpp
 *
 * This is an autogenerated file containing implementations of C functions to be
 * called by the R hmm_loglik binding.
 */
#include <rcpp_mlpack.h>
#define BINDING_TYPE BINDING_TYPE_R
#include <mlpack/methods/hmm/hmm_loglik_main.cpp>

// [[Rcpp::export]]
void hmm_loglik_mlpackMain()
{
  mlpackMain();
}

// Any implementations of methods for dealing with model pointers will be put
// below this comment, if needed.


