/**
 * @file src/hmm_viterbi.cpp
 *
 * This is an autogenerated file containing implementations of C functions to be
 * called by the R hmm_viterbi binding.
 */
#include <rcpp_mlpack.h>
#define BINDING_TYPE BINDING_TYPE_R
#include <mlpack/methods/hmm/hmm_viterbi_main.cpp>

// [[Rcpp::export]]
void hmm_viterbi_mlpackMain()
{
  mlpackMain();
}

// Any implementations of methods for dealing with model pointers will be put
// below this comment, if needed.


