/**
 * @file src/hoeffding_tree.cpp
 *
 * This is an autogenerated file containing implementations of C++ functions to
 * be called by the R hoeffding_tree binding.
 */
#include <rcpp_mlpack.h>
#define BINDING_TYPE BINDING_TYPE_R
#include <mlpack/methods/hoeffding_trees/hoeffding_tree_main.cpp>

// [[Rcpp::export]]
void hoeffding_tree_mlpackMain()
{
  mlpackMain();
}

// Any implementations of methods for dealing with model pointers will be put
// below this comment, if needed.

// Get the pointer to a HoeffdingTreeModel parameter.
// [[Rcpp::export]]
SEXP IO_GetParamHoeffdingTreeModelPtr(const std::string& paramName)
{
  return std::move((Rcpp::XPtr<HoeffdingTreeModel>) IO::GetParam<HoeffdingTreeModel*>(paramName));
}

// Set the pointer to a HoeffdingTreeModel parameter.
// [[Rcpp::export]]
void IO_SetParamHoeffdingTreeModelPtr(const std::string& paramName, SEXP ptr)
{
  IO::GetParam<HoeffdingTreeModel*>(paramName) =  Rcpp::as<Rcpp::XPtr<HoeffdingTreeModel>>(ptr);
  IO::SetPassed(paramName);
}

// Serialize a HoeffdingTreeModel pointer.
// [[Rcpp::export]]
Rcpp::RawVector SerializeHoeffdingTreeModelPtr(SEXP ptr)
{
  std::ostringstream oss;
  {
    cereal::BinaryOutputArchive oa(oss);
    oa << cereal::make_nvp("HoeffdingTreeModel",
          *Rcpp::as<Rcpp::XPtr<HoeffdingTreeModel>>(ptr));
  }

  Rcpp::RawVector raw_vec(oss.str().size());

  // Copy the string buffer so we can return one that won't get deallocated when
  // we exit this function.
  memcpy(&raw_vec[0], oss.str().c_str(), oss.str().size());
  raw_vec.attr("type") = "HoeffdingTreeModel";
  return raw_vec;
}

// Deserialize a HoeffdingTreeModel pointer.
// [[Rcpp::export]]
SEXP DeserializeHoeffdingTreeModelPtr(Rcpp::RawVector str)
{
  HoeffdingTreeModel* ptr = new HoeffdingTreeModel();

  std::istringstream iss(std::string((char *) &str[0], str.size()));
  {
    cereal::BinaryInputArchive ia(iss);
    ia >> cereal::make_nvp("HoeffdingTreeModel", *ptr);
  }

  // R will be responsible for freeing this.
  return std::move((Rcpp::XPtr<HoeffdingTreeModel>)ptr);
}


