/**
 * @file src/image_converter.cpp
 *
 * This is an autogenerated file containing implementations of C functions to be
 * called by the R image_converter binding.
 */
#include <rcpp_mlpack.h>
#define BINDING_TYPE BINDING_TYPE_R
#include <mlpack/methods/preprocess/image_converter_main.cpp>

// [[Rcpp::export]]
void image_converter_mlpackMain()
{
  mlpackMain();
}

// Any implementations of methods for dealing with model pointers will be put
// below this comment, if needed.


