/**
 * @file src/kernel_pca.cpp
 *
 * This is an autogenerated file containing implementations of C functions to be
 * called by the R kernel_pca binding.
 */
#include <rcpp_mlpack.h>
#define BINDING_TYPE BINDING_TYPE_R
#include <mlpack/methods/kernel_pca/kernel_pca_main.cpp>

// [[Rcpp::export]]
void kernel_pca_mlpackMain()
{
  mlpackMain();
}

// Any implementations of methods for dealing with model pointers will be put
// below this comment, if needed.


