/**
 * @file src/local_coordinate_coding.cpp
 *
 * This is an autogenerated file containing implementations of C functions to be
 * called by the R local_coordinate_coding binding.
 */
#include <rcpp_mlpack.h>
#define BINDING_TYPE BINDING_TYPE_R
#include <mlpack/methods/local_coordinate_coding/local_coordinate_coding_main.cpp>

// [[Rcpp::export]]
void local_coordinate_coding_mlpackMain()
{
  mlpackMain();
}

// Any implementations of methods for dealing with model pointers will be put
// below this comment, if needed.

// Get the pointer to a LocalCoordinateCoding parameter.
// [[Rcpp::export]]
SEXP IO_GetParamLocalCoordinateCodingPtr(const std::string& paramName)
{
  return std::move((Rcpp::XPtr<LocalCoordinateCoding>) IO::GetParam<LocalCoordinateCoding*>(paramName));
}

// Set the pointer to a LocalCoordinateCoding parameter.
// [[Rcpp::export]]
void IO_SetParamLocalCoordinateCodingPtr(const std::string& paramName, SEXP ptr)
{
  IO::GetParam<LocalCoordinateCoding*>(paramName) =  Rcpp::as<Rcpp::XPtr<LocalCoordinateCoding>>(ptr);
  IO::SetPassed(paramName);
}

// Serialize a LocalCoordinateCoding pointer.
// [[Rcpp::export]]
Rcpp::RawVector SerializeLocalCoordinateCodingPtr(SEXP ptr)
{
  std::ostringstream oss;
  {
    boost::archive::binary_oarchive oa(oss);
    oa << boost::serialization::make_nvp("LocalCoordinateCoding",
          *Rcpp::as<Rcpp::XPtr<LocalCoordinateCoding>>(ptr));
  }

  Rcpp::RawVector raw_vec(oss.str().size());

  // Copy the string buffer so we can return one that won't get deallocated when
  // we exit this function.
  memcpy(&raw_vec[0], oss.str().c_str(), oss.str().size());
  raw_vec.attr("type") = "LocalCoordinateCoding";
  return raw_vec;
}

// Deserialize a LocalCoordinateCoding pointer.
// [[Rcpp::export]]
SEXP DeserializeLocalCoordinateCodingPtr(Rcpp::RawVector str)
{
  LocalCoordinateCoding* ptr = new LocalCoordinateCoding();

  std::istringstream iss(std::string((char *) &str[0], str.size()));
  {
    boost::archive::binary_iarchive ia(iss);
    ia >> boost::serialization::make_nvp("LocalCoordinateCoding", *ptr);
  }

  // R will be responsible for freeing this.
  return std::move((Rcpp::XPtr<LocalCoordinateCoding>)ptr);
}


