/**
 * @file src/mean_shift.cpp
 *
 * This is an autogenerated file containing implementations of C functions to be
 * called by the R mean_shift binding.
 */
#include <rcpp_mlpack.h>
#define BINDING_TYPE BINDING_TYPE_R
#include <mlpack/methods/mean_shift/mean_shift_main.cpp>

// [[Rcpp::export]]
void mean_shift_mlpackMain()
{
  mlpackMain();
}

// Any implementations of methods for dealing with model pointers will be put
// below this comment, if needed.


