/**
 * @file src/preprocess_describe.cpp
 *
 * This is an autogenerated file containing implementations of C functions to be
 * called by the R preprocess_describe binding.
 */
#include <rcpp_mlpack.h>
#define BINDING_TYPE BINDING_TYPE_R
#include <mlpack/methods/preprocess/preprocess_describe_main.cpp>

// [[Rcpp::export]]
void preprocess_describe_mlpackMain()
{
  mlpackMain();
}

// Any implementations of methods for dealing with model pointers will be put
// below this comment, if needed.


