/**
 * @file src/radical.cpp
 *
 * This is an autogenerated file containing implementations of C functions to be
 * called by the R radical binding.
 */
#include <rcpp_mlpack.h>
#define BINDING_TYPE BINDING_TYPE_R
#include <mlpack/methods/radical/radical_main.cpp>

// [[Rcpp::export]]
void radical_mlpackMain()
{
  mlpackMain();
}

// Any implementations of methods for dealing with model pointers will be put
// below this comment, if needed.


