/**
 * @file src/range_search.cpp
 *
 * This is an autogenerated file containing implementations of C functions to be
 * called by the R range_search binding.
 */
#include <rcpp_mlpack.h>
#define BINDING_TYPE BINDING_TYPE_R
#include <mlpack/methods/range_search/range_search_main.cpp>

// [[Rcpp::export]]
void range_search_mlpackMain()
{
  mlpackMain();
}

// Any implementations of methods for dealing with model pointers will be put
// below this comment, if needed.

// Get the pointer to a RSModel parameter.
// [[Rcpp::export]]
SEXP IO_GetParamRSModelPtr(const std::string& paramName)
{
  return std::move((Rcpp::XPtr<RSModel>) IO::GetParam<RSModel*>(paramName));
}

// Set the pointer to a RSModel parameter.
// [[Rcpp::export]]
void IO_SetParamRSModelPtr(const std::string& paramName, SEXP ptr)
{
  IO::GetParam<RSModel*>(paramName) =  Rcpp::as<Rcpp::XPtr<RSModel>>(ptr);
  IO::SetPassed(paramName);
}

// Serialize a RSModel pointer.
// [[Rcpp::export]]
Rcpp::RawVector SerializeRSModelPtr(SEXP ptr)
{
  std::ostringstream oss;
  {
    boost::archive::binary_oarchive oa(oss);
    oa << boost::serialization::make_nvp("RSModel",
          *Rcpp::as<Rcpp::XPtr<RSModel>>(ptr));
  }

  Rcpp::RawVector raw_vec(oss.str().size());

  // Copy the string buffer so we can return one that won't get deallocated when
  // we exit this function.
  memcpy(&raw_vec[0], oss.str().c_str(), oss.str().size());
  raw_vec.attr("type") = "RSModel";
  return raw_vec;
}

// Deserialize a RSModel pointer.
// [[Rcpp::export]]
SEXP DeserializeRSModelPtr(Rcpp::RawVector str)
{
  RSModel* ptr = new RSModel();

  std::istringstream iss(std::string((char *) &str[0], str.size()));
  {
    boost::archive::binary_iarchive ia(iss);
    ia >> boost::serialization::make_nvp("RSModel", *ptr);
  }

  // R will be responsible for freeing this.
  return std::move((Rcpp::XPtr<RSModel>)ptr);
}


