// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppMLPACK.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// CLI_RestoreSettings
SEXP CLI_RestoreSettings(SEXP programName);
RcppExport SEXP _RcppMLPACK_CLI_RestoreSettings(SEXP programNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type programName(programNameSEXP);
    rcpp_result_gen = Rcpp::wrap(CLI_RestoreSettings(programName));
    return rcpp_result_gen;
END_RCPP
}
// CLI_SetParamInt
SEXP CLI_SetParamInt(SEXP paramName, SEXP paramValue);
RcppExport SEXP _RcppMLPACK_CLI_SetParamInt(SEXP paramNameSEXP, SEXP paramValueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type paramName(paramNameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type paramValue(paramValueSEXP);
    rcpp_result_gen = Rcpp::wrap(CLI_SetParamInt(paramName, paramValue));
    return rcpp_result_gen;
END_RCPP
}
// CLI_SetParamDouble
SEXP CLI_SetParamDouble(SEXP paramName, SEXP paramValue);
RcppExport SEXP _RcppMLPACK_CLI_SetParamDouble(SEXP paramNameSEXP, SEXP paramValueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type paramName(paramNameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type paramValue(paramValueSEXP);
    rcpp_result_gen = Rcpp::wrap(CLI_SetParamDouble(paramName, paramValue));
    return rcpp_result_gen;
END_RCPP
}
// CLI_SetParamString
SEXP CLI_SetParamString(SEXP paramName, SEXP paramValue);
RcppExport SEXP _RcppMLPACK_CLI_SetParamString(SEXP paramNameSEXP, SEXP paramValueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type paramName(paramNameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type paramValue(paramValueSEXP);
    rcpp_result_gen = Rcpp::wrap(CLI_SetParamString(paramName, paramValue));
    return rcpp_result_gen;
END_RCPP
}
// CLI_SetParamBool
SEXP CLI_SetParamBool(SEXP paramName, SEXP paramValue);
RcppExport SEXP _RcppMLPACK_CLI_SetParamBool(SEXP paramNameSEXP, SEXP paramValueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type paramName(paramNameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type paramValue(paramValueSEXP);
    rcpp_result_gen = Rcpp::wrap(CLI_SetParamBool(paramName, paramValue));
    return rcpp_result_gen;
END_RCPP
}
// CLI_SetParamMat
SEXP CLI_SetParamMat(SEXP paramName, SEXP paramValue);
RcppExport SEXP _RcppMLPACK_CLI_SetParamMat(SEXP paramNameSEXP, SEXP paramValueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type paramName(paramNameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type paramValue(paramValueSEXP);
    rcpp_result_gen = Rcpp::wrap(CLI_SetParamMat(paramName, paramValue));
    return rcpp_result_gen;
END_RCPP
}
// CLI_GetParamInt
SEXP CLI_GetParamInt(SEXP paramName);
RcppExport SEXP _RcppMLPACK_CLI_GetParamInt(SEXP paramNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type paramName(paramNameSEXP);
    rcpp_result_gen = Rcpp::wrap(CLI_GetParamInt(paramName));
    return rcpp_result_gen;
END_RCPP
}
// CLI_GetParamDouble
SEXP CLI_GetParamDouble(SEXP paramName);
RcppExport SEXP _RcppMLPACK_CLI_GetParamDouble(SEXP paramNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type paramName(paramNameSEXP);
    rcpp_result_gen = Rcpp::wrap(CLI_GetParamDouble(paramName));
    return rcpp_result_gen;
END_RCPP
}
// CLI_GetParamString
SEXP CLI_GetParamString(SEXP paramName);
RcppExport SEXP _RcppMLPACK_CLI_GetParamString(SEXP paramNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type paramName(paramNameSEXP);
    rcpp_result_gen = Rcpp::wrap(CLI_GetParamString(paramName));
    return rcpp_result_gen;
END_RCPP
}
// CLI_GetParamBool
SEXP CLI_GetParamBool(SEXP paramName);
RcppExport SEXP _RcppMLPACK_CLI_GetParamBool(SEXP paramNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type paramName(paramNameSEXP);
    rcpp_result_gen = Rcpp::wrap(CLI_GetParamBool(paramName));
    return rcpp_result_gen;
END_RCPP
}
// CLI_GetParamMatRows
SEXP CLI_GetParamMatRows(SEXP paramName);
RcppExport SEXP _RcppMLPACK_CLI_GetParamMatRows(SEXP paramNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type paramName(paramNameSEXP);
    rcpp_result_gen = Rcpp::wrap(CLI_GetParamMatRows(paramName));
    return rcpp_result_gen;
END_RCPP
}
// CLI_GetParamMatCols
SEXP CLI_GetParamMatCols(SEXP paramName);
RcppExport SEXP _RcppMLPACK_CLI_GetParamMatCols(SEXP paramNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type paramName(paramNameSEXP);
    rcpp_result_gen = Rcpp::wrap(CLI_GetParamMatCols(paramName));
    return rcpp_result_gen;
END_RCPP
}
// CLI_GetParamMat
SEXP CLI_GetParamMat(SEXP paramName);
RcppExport SEXP _RcppMLPACK_CLI_GetParamMat(SEXP paramNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type paramName(paramNameSEXP);
    rcpp_result_gen = Rcpp::wrap(CLI_GetParamMat(paramName));
    return rcpp_result_gen;
END_RCPP
}
// CLI_EnableVerbose
SEXP CLI_EnableVerbose();
RcppExport SEXP _RcppMLPACK_CLI_EnableVerbose() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(CLI_EnableVerbose());
    return rcpp_result_gen;
END_RCPP
}
// CLI_DisableVerbose
SEXP CLI_DisableVerbose();
RcppExport SEXP _RcppMLPACK_CLI_DisableVerbose() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(CLI_DisableVerbose());
    return rcpp_result_gen;
END_RCPP
}
// CLI_ResetTimers
SEXP CLI_ResetTimers();
RcppExport SEXP _RcppMLPACK_CLI_ResetTimers() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(CLI_ResetTimers());
    return rcpp_result_gen;
END_RCPP
}
// CLI_SetPassed
SEXP CLI_SetPassed(SEXP paramName);
RcppExport SEXP _RcppMLPACK_CLI_SetPassed(SEXP paramNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type paramName(paramNameSEXP);
    rcpp_result_gen = Rcpp::wrap(CLI_SetPassed(paramName));
    return rcpp_result_gen;
END_RCPP
}
// CLI_ClearSettings
SEXP CLI_ClearSettings();
RcppExport SEXP _RcppMLPACK_CLI_ClearSettings() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(CLI_ClearSettings());
    return rcpp_result_gen;
END_RCPP
}
// test_r_binding_mlpackMain
SEXP test_r_binding_mlpackMain();
RcppExport SEXP _RcppMLPACK_test_r_binding_mlpackMain() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_r_binding_mlpackMain());
    return rcpp_result_gen;
END_RCPP
}
// CLI_GetParamGaussianKernelPtr
SEXP CLI_GetParamGaussianKernelPtr(SEXP paramName);
RcppExport SEXP _RcppMLPACK_CLI_GetParamGaussianKernelPtr(SEXP paramNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type paramName(paramNameSEXP);
    rcpp_result_gen = Rcpp::wrap(CLI_GetParamGaussianKernelPtr(paramName));
    return rcpp_result_gen;
END_RCPP
}
// CLI_SetParamGaussianKernelPtr
SEXP CLI_SetParamGaussianKernelPtr(SEXP paramName, SEXP ptr);
RcppExport SEXP _RcppMLPACK_CLI_SetParamGaussianKernelPtr(SEXP paramNameSEXP, SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type paramName(paramNameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(CLI_SetParamGaussianKernelPtr(paramName, ptr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RcppMLPACK_CLI_RestoreSettings", (DL_FUNC) &_RcppMLPACK_CLI_RestoreSettings, 1},
    {"_RcppMLPACK_CLI_SetParamInt", (DL_FUNC) &_RcppMLPACK_CLI_SetParamInt, 2},
    {"_RcppMLPACK_CLI_SetParamDouble", (DL_FUNC) &_RcppMLPACK_CLI_SetParamDouble, 2},
    {"_RcppMLPACK_CLI_SetParamString", (DL_FUNC) &_RcppMLPACK_CLI_SetParamString, 2},
    {"_RcppMLPACK_CLI_SetParamBool", (DL_FUNC) &_RcppMLPACK_CLI_SetParamBool, 2},
    {"_RcppMLPACK_CLI_SetParamMat", (DL_FUNC) &_RcppMLPACK_CLI_SetParamMat, 2},
    {"_RcppMLPACK_CLI_GetParamInt", (DL_FUNC) &_RcppMLPACK_CLI_GetParamInt, 1},
    {"_RcppMLPACK_CLI_GetParamDouble", (DL_FUNC) &_RcppMLPACK_CLI_GetParamDouble, 1},
    {"_RcppMLPACK_CLI_GetParamString", (DL_FUNC) &_RcppMLPACK_CLI_GetParamString, 1},
    {"_RcppMLPACK_CLI_GetParamBool", (DL_FUNC) &_RcppMLPACK_CLI_GetParamBool, 1},
    {"_RcppMLPACK_CLI_GetParamMatRows", (DL_FUNC) &_RcppMLPACK_CLI_GetParamMatRows, 1},
    {"_RcppMLPACK_CLI_GetParamMatCols", (DL_FUNC) &_RcppMLPACK_CLI_GetParamMatCols, 1},
    {"_RcppMLPACK_CLI_GetParamMat", (DL_FUNC) &_RcppMLPACK_CLI_GetParamMat, 1},
    {"_RcppMLPACK_CLI_EnableVerbose", (DL_FUNC) &_RcppMLPACK_CLI_EnableVerbose, 0},
    {"_RcppMLPACK_CLI_DisableVerbose", (DL_FUNC) &_RcppMLPACK_CLI_DisableVerbose, 0},
    {"_RcppMLPACK_CLI_ResetTimers", (DL_FUNC) &_RcppMLPACK_CLI_ResetTimers, 0},
    {"_RcppMLPACK_CLI_SetPassed", (DL_FUNC) &_RcppMLPACK_CLI_SetPassed, 1},
    {"_RcppMLPACK_CLI_ClearSettings", (DL_FUNC) &_RcppMLPACK_CLI_ClearSettings, 0},
    {"_RcppMLPACK_test_r_binding_mlpackMain", (DL_FUNC) &_RcppMLPACK_test_r_binding_mlpackMain, 0},
    {"_RcppMLPACK_CLI_GetParamGaussianKernelPtr", (DL_FUNC) &_RcppMLPACK_CLI_GetParamGaussianKernelPtr, 1},
    {"_RcppMLPACK_CLI_SetParamGaussianKernelPtr", (DL_FUNC) &_RcppMLPACK_CLI_SetParamGaussianKernelPtr, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RcppMLPACK(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
