# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adaboost_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_adaboost_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamAdaBoostModelPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamAdaBoostModelPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamAdaBoostModelPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamAdaBoostModelPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeAdaBoostModelPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeAdaBoostModelPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeAdaBoostModelPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeAdaBoostModelPtr', PACKAGE = 'RcppMLPACK', str)
}

approx_kfn_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_approx_kfn_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamApproxKFNModelPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamApproxKFNModelPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamApproxKFNModelPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamApproxKFNModelPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeApproxKFNModelPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeApproxKFNModelPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeApproxKFNModelPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeApproxKFNModelPtr', PACKAGE = 'RcppMLPACK', str)
}

dbscan_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_dbscan_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

decision_stump_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_decision_stump_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamDSModelPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamDSModelPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamDSModelPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamDSModelPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeDSModelPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeDSModelPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeDSModelPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeDSModelPtr', PACKAGE = 'RcppMLPACK', str)
}

decision_tree_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_decision_tree_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamDecisionTreeModelPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamDecisionTreeModelPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamDecisionTreeModelPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamDecisionTreeModelPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeDecisionTreeModelPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeDecisionTreeModelPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeDecisionTreeModelPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeDecisionTreeModelPtr', PACKAGE = 'RcppMLPACK', str)
}

det_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_det_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamDTreePtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamDTreePtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamDTreePtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamDTreePtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeDTreePtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeDTreePtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeDTreePtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeDTreePtr', PACKAGE = 'RcppMLPACK', str)
}

emst_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_emst_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

fastmks_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_fastmks_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamFastMKSModelPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamFastMKSModelPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamFastMKSModelPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamFastMKSModelPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeFastMKSModelPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeFastMKSModelPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeFastMKSModelPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeFastMKSModelPtr', PACKAGE = 'RcppMLPACK', str)
}

gmm_generate_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_gmm_generate_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamGMMPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamGMMPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamGMMPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamGMMPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeGMMPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeGMMPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeGMMPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeGMMPtr', PACKAGE = 'RcppMLPACK', str)
}

gmm_probability_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_gmm_probability_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

gmm_train_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_gmm_train_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

hmm_generate_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_hmm_generate_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamHMMModelPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamHMMModelPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamHMMModelPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamHMMModelPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeHMMModelPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeHMMModelPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeHMMModelPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeHMMModelPtr', PACKAGE = 'RcppMLPACK', str)
}

hmm_loglik_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_hmm_loglik_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

hmm_train_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_hmm_train_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

hmm_viterbi_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_hmm_viterbi_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

hoeffding_tree_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_hoeffding_tree_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamHoeffdingTreeModelPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamHoeffdingTreeModelPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamHoeffdingTreeModelPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamHoeffdingTreeModelPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeHoeffdingTreeModelPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeHoeffdingTreeModelPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeHoeffdingTreeModelPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeHoeffdingTreeModelPtr', PACKAGE = 'RcppMLPACK', str)
}

image_converter_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_image_converter_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

kde_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_kde_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamKDEModelPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamKDEModelPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamKDEModelPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamKDEModelPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeKDEModelPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeKDEModelPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeKDEModelPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeKDEModelPtr', PACKAGE = 'RcppMLPACK', str)
}

kernel_pca_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_kernel_pca_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

kfn_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_kfn_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamKFNModelPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamKFNModelPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamKFNModelPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamKFNModelPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeKFNModelPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeKFNModelPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeKFNModelPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeKFNModelPtr', PACKAGE = 'RcppMLPACK', str)
}

kmeans_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_kmeans_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

knn_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_knn_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamKNNModelPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamKNNModelPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamKNNModelPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamKNNModelPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeKNNModelPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeKNNModelPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeKNNModelPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeKNNModelPtr', PACKAGE = 'RcppMLPACK', str)
}

krann_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_krann_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamRANNModelPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamRANNModelPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamRANNModelPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamRANNModelPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeRANNModelPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeRANNModelPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeRANNModelPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeRANNModelPtr', PACKAGE = 'RcppMLPACK', str)
}

lars_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_lars_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamLARSPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamLARSPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamLARSPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamLARSPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeLARSPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeLARSPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeLARSPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeLARSPtr', PACKAGE = 'RcppMLPACK', str)
}

linear_regression_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_linear_regression_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamLinearRegressionPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamLinearRegressionPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamLinearRegressionPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamLinearRegressionPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeLinearRegressionPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeLinearRegressionPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeLinearRegressionPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeLinearRegressionPtr', PACKAGE = 'RcppMLPACK', str)
}

linear_svm_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_linear_svm_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamLinearSVMModelPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamLinearSVMModelPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamLinearSVMModelPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamLinearSVMModelPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeLinearSVMModelPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeLinearSVMModelPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeLinearSVMModelPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeLinearSVMModelPtr', PACKAGE = 'RcppMLPACK', str)
}

lmnn_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_lmnn_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

local_coordinate_coding_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_local_coordinate_coding_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamLocalCoordinateCodingPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamLocalCoordinateCodingPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamLocalCoordinateCodingPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamLocalCoordinateCodingPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeLocalCoordinateCodingPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeLocalCoordinateCodingPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeLocalCoordinateCodingPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeLocalCoordinateCodingPtr', PACKAGE = 'RcppMLPACK', str)
}

logistic_regression_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_logistic_regression_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamLogisticRegressionPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamLogisticRegressionPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamLogisticRegressionPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamLogisticRegressionPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeLogisticRegressionPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeLogisticRegressionPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeLogisticRegressionPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeLogisticRegressionPtr', PACKAGE = 'RcppMLPACK', str)
}

lsh_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_lsh_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamLSHSearchPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamLSHSearchPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamLSHSearchPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamLSHSearchPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeLSHSearchPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeLSHSearchPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeLSHSearchPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeLSHSearchPtr', PACKAGE = 'RcppMLPACK', str)
}

mean_shift_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_mean_shift_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

nbc_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_nbc_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamNBCModelPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamNBCModelPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamNBCModelPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamNBCModelPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeNBCModelPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeNBCModelPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeNBCModelPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeNBCModelPtr', PACKAGE = 'RcppMLPACK', str)
}

nca_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_nca_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

nmf_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_nmf_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

pca_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_pca_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

perceptron_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_perceptron_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamPerceptronModelPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamPerceptronModelPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamPerceptronModelPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamPerceptronModelPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializePerceptronModelPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializePerceptronModelPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializePerceptronModelPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializePerceptronModelPtr', PACKAGE = 'RcppMLPACK', str)
}

preprocess_binarize_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_preprocess_binarize_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

preprocess_describe_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_preprocess_describe_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

preprocess_scale_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_preprocess_scale_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamScalingModelPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamScalingModelPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamScalingModelPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamScalingModelPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeScalingModelPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeScalingModelPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeScalingModelPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeScalingModelPtr', PACKAGE = 'RcppMLPACK', str)
}

preprocess_split_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_preprocess_split_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_RestoreSettings <- function(programName) {
    invisible(.Call('_RcppMLPACK_CLI_RestoreSettings', PACKAGE = 'RcppMLPACK', programName))
}

CLI_SetParamInt <- function(paramName, paramValue) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamInt', PACKAGE = 'RcppMLPACK', paramName, paramValue))
}

CLI_SetParamDouble <- function(paramName, paramValue) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamDouble', PACKAGE = 'RcppMLPACK', paramName, paramValue))
}

CLI_SetParamString <- function(paramName, paramValue) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamString', PACKAGE = 'RcppMLPACK', paramName, paramValue))
}

CLI_SetParamBool <- function(paramName, paramValue) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamBool', PACKAGE = 'RcppMLPACK', paramName, paramValue))
}

CLI_SetParamVecString <- function(paramName, str) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamVecString', PACKAGE = 'RcppMLPACK', paramName, str))
}

CLI_SetParamVecInt <- function(paramName, ints) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamVecInt', PACKAGE = 'RcppMLPACK', paramName, ints))
}

CLI_SetParamMat <- function(paramName, paramValue) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamMat', PACKAGE = 'RcppMLPACK', paramName, paramValue))
}

CLI_SetParamUMat <- function(paramName, paramValue) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamUMat', PACKAGE = 'RcppMLPACK', paramName, paramValue))
}

CLI_SetParamRow <- function(paramName, paramValue) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamRow', PACKAGE = 'RcppMLPACK', paramName, paramValue))
}

CLI_SetParamURow <- function(paramName, paramValue) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamURow', PACKAGE = 'RcppMLPACK', paramName, paramValue))
}

CLI_SetParamCol <- function(paramName, paramValue) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamCol', PACKAGE = 'RcppMLPACK', paramName, paramValue))
}

CLI_SetParamUCol <- function(paramName, paramValue) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamUCol', PACKAGE = 'RcppMLPACK', paramName, paramValue))
}

CLI_SetParamMatWithInfo <- function(paramName, dimensions, paramValue) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamMatWithInfo', PACKAGE = 'RcppMLPACK', paramName, dimensions, paramValue))
}

CLI_GetParamInt <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamInt', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_GetParamDouble <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamDouble', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_GetParamString <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamString', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_GetParamBool <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamBool', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_GetParamVecString <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamVecString', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_GetParamVecInt <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamVecInt', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_GetParamMat <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamMat', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_GetParamUMat <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamUMat', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_GetParamRow <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamRow', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_GetParamURow <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamURow', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_GetParamCol <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamCol', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_GetParamUCol <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamUCol', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_GetParamMatWithInfo <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamMatWithInfo', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_EnableVerbose <- function() {
    invisible(.Call('_RcppMLPACK_CLI_EnableVerbose', PACKAGE = 'RcppMLPACK'))
}

CLI_DisableVerbose <- function() {
    invisible(.Call('_RcppMLPACK_CLI_DisableVerbose', PACKAGE = 'RcppMLPACK'))
}

CLI_ResetTimers <- function() {
    invisible(.Call('_RcppMLPACK_CLI_ResetTimers', PACKAGE = 'RcppMLPACK'))
}

CLI_SetPassed <- function(paramName) {
    invisible(.Call('_RcppMLPACK_CLI_SetPassed', PACKAGE = 'RcppMLPACK', paramName))
}

CLI_ClearSettings <- function() {
    invisible(.Call('_RcppMLPACK_CLI_ClearSettings', PACKAGE = 'RcppMLPACK'))
}

radical_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_radical_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

random_forest_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_random_forest_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamRandomForestModelPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamRandomForestModelPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamRandomForestModelPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamRandomForestModelPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeRandomForestModelPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeRandomForestModelPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeRandomForestModelPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeRandomForestModelPtr', PACKAGE = 'RcppMLPACK', str)
}

range_search_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_range_search_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamRSModelPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamRSModelPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamRSModelPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamRSModelPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeRSModelPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeRSModelPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeRSModelPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeRSModelPtr', PACKAGE = 'RcppMLPACK', str)
}

softmax_regression_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_softmax_regression_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamSoftmaxRegressionPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamSoftmaxRegressionPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamSoftmaxRegressionPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamSoftmaxRegressionPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeSoftmaxRegressionPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeSoftmaxRegressionPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeSoftmaxRegressionPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeSoftmaxRegressionPtr', PACKAGE = 'RcppMLPACK', str)
}

sparse_coding_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_sparse_coding_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamSparseCodingPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamSparseCodingPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamSparseCodingPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamSparseCodingPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeSparseCodingPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeSparseCodingPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeSparseCodingPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeSparseCodingPtr', PACKAGE = 'RcppMLPACK', str)
}

test_r_binding_mlpackMain <- function() {
    invisible(.Call('_RcppMLPACK_test_r_binding_mlpackMain', PACKAGE = 'RcppMLPACK'))
}

CLI_GetParamGaussianKernelPtr <- function(paramName) {
    .Call('_RcppMLPACK_CLI_GetParamGaussianKernelPtr', PACKAGE = 'RcppMLPACK', paramName)
}

CLI_SetParamGaussianKernelPtr <- function(paramName, ptr) {
    invisible(.Call('_RcppMLPACK_CLI_SetParamGaussianKernelPtr', PACKAGE = 'RcppMLPACK', paramName, ptr))
}

SerializeGaussianKernelPtr <- function(ptr) {
    .Call('_RcppMLPACK_SerializeGaussianKernelPtr', PACKAGE = 'RcppMLPACK', ptr)
}

DeserializeGaussianKernelPtr <- function(str) {
    .Call('_RcppMLPACK_DeserializeGaussianKernelPtr', PACKAGE = 'RcppMLPACK', str)
}

