# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adaboost_mlpackMain <- function() {
    invisible(.Call('_mlpack_adaboost_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamAdaBoostModelPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamAdaBoostModelPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamAdaBoostModelPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamAdaBoostModelPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeAdaBoostModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeAdaBoostModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeAdaBoostModelPtr <- function(str) {
    .Call('_mlpack_DeserializeAdaBoostModelPtr', PACKAGE = 'mlpack', str)
}

approx_kfn_mlpackMain <- function() {
    invisible(.Call('_mlpack_approx_kfn_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamApproxKFNModelPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamApproxKFNModelPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamApproxKFNModelPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamApproxKFNModelPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeApproxKFNModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeApproxKFNModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeApproxKFNModelPtr <- function(str) {
    .Call('_mlpack_DeserializeApproxKFNModelPtr', PACKAGE = 'mlpack', str)
}

cf_mlpackMain <- function() {
    invisible(.Call('_mlpack_cf_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamCFModelPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamCFModelPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamCFModelPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamCFModelPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeCFModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeCFModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeCFModelPtr <- function(str) {
    .Call('_mlpack_DeserializeCFModelPtr', PACKAGE = 'mlpack', str)
}

dbscan_mlpackMain <- function() {
    invisible(.Call('_mlpack_dbscan_mlpackMain', PACKAGE = 'mlpack'))
}

decision_stump_mlpackMain <- function() {
    invisible(.Call('_mlpack_decision_stump_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamDSModelPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamDSModelPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamDSModelPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamDSModelPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeDSModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeDSModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeDSModelPtr <- function(str) {
    .Call('_mlpack_DeserializeDSModelPtr', PACKAGE = 'mlpack', str)
}

decision_tree_mlpackMain <- function() {
    invisible(.Call('_mlpack_decision_tree_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamDecisionTreeModelPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamDecisionTreeModelPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamDecisionTreeModelPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamDecisionTreeModelPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeDecisionTreeModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeDecisionTreeModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeDecisionTreeModelPtr <- function(str) {
    .Call('_mlpack_DeserializeDecisionTreeModelPtr', PACKAGE = 'mlpack', str)
}

det_mlpackMain <- function() {
    invisible(.Call('_mlpack_det_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamDTreePtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamDTreePtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamDTreePtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamDTreePtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeDTreePtr <- function(ptr) {
    .Call('_mlpack_SerializeDTreePtr', PACKAGE = 'mlpack', ptr)
}

DeserializeDTreePtr <- function(str) {
    .Call('_mlpack_DeserializeDTreePtr', PACKAGE = 'mlpack', str)
}

emst_mlpackMain <- function() {
    invisible(.Call('_mlpack_emst_mlpackMain', PACKAGE = 'mlpack'))
}

fastmks_mlpackMain <- function() {
    invisible(.Call('_mlpack_fastmks_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamFastMKSModelPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamFastMKSModelPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamFastMKSModelPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamFastMKSModelPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeFastMKSModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeFastMKSModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeFastMKSModelPtr <- function(str) {
    .Call('_mlpack_DeserializeFastMKSModelPtr', PACKAGE = 'mlpack', str)
}

gmm_generate_mlpackMain <- function() {
    invisible(.Call('_mlpack_gmm_generate_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamGMMPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamGMMPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamGMMPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamGMMPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeGMMPtr <- function(ptr) {
    .Call('_mlpack_SerializeGMMPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeGMMPtr <- function(str) {
    .Call('_mlpack_DeserializeGMMPtr', PACKAGE = 'mlpack', str)
}

gmm_probability_mlpackMain <- function() {
    invisible(.Call('_mlpack_gmm_probability_mlpackMain', PACKAGE = 'mlpack'))
}

gmm_train_mlpackMain <- function() {
    invisible(.Call('_mlpack_gmm_train_mlpackMain', PACKAGE = 'mlpack'))
}

hmm_generate_mlpackMain <- function() {
    invisible(.Call('_mlpack_hmm_generate_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamHMMModelPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamHMMModelPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamHMMModelPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamHMMModelPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeHMMModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeHMMModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeHMMModelPtr <- function(str) {
    .Call('_mlpack_DeserializeHMMModelPtr', PACKAGE = 'mlpack', str)
}

hmm_loglik_mlpackMain <- function() {
    invisible(.Call('_mlpack_hmm_loglik_mlpackMain', PACKAGE = 'mlpack'))
}

hmm_train_mlpackMain <- function() {
    invisible(.Call('_mlpack_hmm_train_mlpackMain', PACKAGE = 'mlpack'))
}

hmm_viterbi_mlpackMain <- function() {
    invisible(.Call('_mlpack_hmm_viterbi_mlpackMain', PACKAGE = 'mlpack'))
}

hoeffding_tree_mlpackMain <- function() {
    invisible(.Call('_mlpack_hoeffding_tree_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamHoeffdingTreeModelPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamHoeffdingTreeModelPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamHoeffdingTreeModelPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamHoeffdingTreeModelPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeHoeffdingTreeModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeHoeffdingTreeModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeHoeffdingTreeModelPtr <- function(str) {
    .Call('_mlpack_DeserializeHoeffdingTreeModelPtr', PACKAGE = 'mlpack', str)
}

image_converter_mlpackMain <- function() {
    invisible(.Call('_mlpack_image_converter_mlpackMain', PACKAGE = 'mlpack'))
}

kde_mlpackMain <- function() {
    invisible(.Call('_mlpack_kde_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamKDEModelPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamKDEModelPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamKDEModelPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamKDEModelPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeKDEModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeKDEModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeKDEModelPtr <- function(str) {
    .Call('_mlpack_DeserializeKDEModelPtr', PACKAGE = 'mlpack', str)
}

kernel_pca_mlpackMain <- function() {
    invisible(.Call('_mlpack_kernel_pca_mlpackMain', PACKAGE = 'mlpack'))
}

kfn_mlpackMain <- function() {
    invisible(.Call('_mlpack_kfn_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamKFNModelPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamKFNModelPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamKFNModelPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamKFNModelPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeKFNModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeKFNModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeKFNModelPtr <- function(str) {
    .Call('_mlpack_DeserializeKFNModelPtr', PACKAGE = 'mlpack', str)
}

kmeans_mlpackMain <- function() {
    invisible(.Call('_mlpack_kmeans_mlpackMain', PACKAGE = 'mlpack'))
}

knn_mlpackMain <- function() {
    invisible(.Call('_mlpack_knn_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamKNNModelPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamKNNModelPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamKNNModelPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamKNNModelPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeKNNModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeKNNModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeKNNModelPtr <- function(str) {
    .Call('_mlpack_DeserializeKNNModelPtr', PACKAGE = 'mlpack', str)
}

krann_mlpackMain <- function() {
    invisible(.Call('_mlpack_krann_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamRANNModelPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamRANNModelPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamRANNModelPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamRANNModelPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeRANNModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeRANNModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeRANNModelPtr <- function(str) {
    .Call('_mlpack_DeserializeRANNModelPtr', PACKAGE = 'mlpack', str)
}

lars_mlpackMain <- function() {
    invisible(.Call('_mlpack_lars_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamLARSPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamLARSPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamLARSPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamLARSPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeLARSPtr <- function(ptr) {
    .Call('_mlpack_SerializeLARSPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeLARSPtr <- function(str) {
    .Call('_mlpack_DeserializeLARSPtr', PACKAGE = 'mlpack', str)
}

linear_regression_mlpackMain <- function() {
    invisible(.Call('_mlpack_linear_regression_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamLinearRegressionPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamLinearRegressionPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamLinearRegressionPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamLinearRegressionPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeLinearRegressionPtr <- function(ptr) {
    .Call('_mlpack_SerializeLinearRegressionPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeLinearRegressionPtr <- function(str) {
    .Call('_mlpack_DeserializeLinearRegressionPtr', PACKAGE = 'mlpack', str)
}

linear_svm_mlpackMain <- function() {
    invisible(.Call('_mlpack_linear_svm_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamLinearSVMModelPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamLinearSVMModelPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamLinearSVMModelPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamLinearSVMModelPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeLinearSVMModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeLinearSVMModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeLinearSVMModelPtr <- function(str) {
    .Call('_mlpack_DeserializeLinearSVMModelPtr', PACKAGE = 'mlpack', str)
}

lmnn_mlpackMain <- function() {
    invisible(.Call('_mlpack_lmnn_mlpackMain', PACKAGE = 'mlpack'))
}

local_coordinate_coding_mlpackMain <- function() {
    invisible(.Call('_mlpack_local_coordinate_coding_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamLocalCoordinateCodingPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamLocalCoordinateCodingPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamLocalCoordinateCodingPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamLocalCoordinateCodingPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeLocalCoordinateCodingPtr <- function(ptr) {
    .Call('_mlpack_SerializeLocalCoordinateCodingPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeLocalCoordinateCodingPtr <- function(str) {
    .Call('_mlpack_DeserializeLocalCoordinateCodingPtr', PACKAGE = 'mlpack', str)
}

logistic_regression_mlpackMain <- function() {
    invisible(.Call('_mlpack_logistic_regression_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamLogisticRegressionPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamLogisticRegressionPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamLogisticRegressionPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamLogisticRegressionPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeLogisticRegressionPtr <- function(ptr) {
    .Call('_mlpack_SerializeLogisticRegressionPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeLogisticRegressionPtr <- function(str) {
    .Call('_mlpack_DeserializeLogisticRegressionPtr', PACKAGE = 'mlpack', str)
}

lsh_mlpackMain <- function() {
    invisible(.Call('_mlpack_lsh_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamLSHSearchPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamLSHSearchPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamLSHSearchPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamLSHSearchPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeLSHSearchPtr <- function(ptr) {
    .Call('_mlpack_SerializeLSHSearchPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeLSHSearchPtr <- function(str) {
    .Call('_mlpack_DeserializeLSHSearchPtr', PACKAGE = 'mlpack', str)
}

mean_shift_mlpackMain <- function() {
    invisible(.Call('_mlpack_mean_shift_mlpackMain', PACKAGE = 'mlpack'))
}

nbc_mlpackMain <- function() {
    invisible(.Call('_mlpack_nbc_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamNBCModelPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamNBCModelPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamNBCModelPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamNBCModelPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeNBCModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeNBCModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeNBCModelPtr <- function(str) {
    .Call('_mlpack_DeserializeNBCModelPtr', PACKAGE = 'mlpack', str)
}

nca_mlpackMain <- function() {
    invisible(.Call('_mlpack_nca_mlpackMain', PACKAGE = 'mlpack'))
}

nmf_mlpackMain <- function() {
    invisible(.Call('_mlpack_nmf_mlpackMain', PACKAGE = 'mlpack'))
}

pca_mlpackMain <- function() {
    invisible(.Call('_mlpack_pca_mlpackMain', PACKAGE = 'mlpack'))
}

perceptron_mlpackMain <- function() {
    invisible(.Call('_mlpack_perceptron_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamPerceptronModelPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamPerceptronModelPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamPerceptronModelPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamPerceptronModelPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializePerceptronModelPtr <- function(ptr) {
    .Call('_mlpack_SerializePerceptronModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializePerceptronModelPtr <- function(str) {
    .Call('_mlpack_DeserializePerceptronModelPtr', PACKAGE = 'mlpack', str)
}

preprocess_binarize_mlpackMain <- function() {
    invisible(.Call('_mlpack_preprocess_binarize_mlpackMain', PACKAGE = 'mlpack'))
}

preprocess_describe_mlpackMain <- function() {
    invisible(.Call('_mlpack_preprocess_describe_mlpackMain', PACKAGE = 'mlpack'))
}

preprocess_scale_mlpackMain <- function() {
    invisible(.Call('_mlpack_preprocess_scale_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamScalingModelPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamScalingModelPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamScalingModelPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamScalingModelPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeScalingModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeScalingModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeScalingModelPtr <- function(str) {
    .Call('_mlpack_DeserializeScalingModelPtr', PACKAGE = 'mlpack', str)
}

preprocess_split_mlpackMain <- function() {
    invisible(.Call('_mlpack_preprocess_split_mlpackMain', PACKAGE = 'mlpack'))
}

IO_RestoreSettings <- function(programName) {
    invisible(.Call('_mlpack_IO_RestoreSettings', PACKAGE = 'mlpack', programName))
}

IO_SetParamInt <- function(paramName, paramValue) {
    invisible(.Call('_mlpack_IO_SetParamInt', PACKAGE = 'mlpack', paramName, paramValue))
}

IO_SetParamDouble <- function(paramName, paramValue) {
    invisible(.Call('_mlpack_IO_SetParamDouble', PACKAGE = 'mlpack', paramName, paramValue))
}

IO_SetParamString <- function(paramName, paramValue) {
    invisible(.Call('_mlpack_IO_SetParamString', PACKAGE = 'mlpack', paramName, paramValue))
}

IO_SetParamBool <- function(paramName, paramValue) {
    invisible(.Call('_mlpack_IO_SetParamBool', PACKAGE = 'mlpack', paramName, paramValue))
}

IO_SetParamVecString <- function(paramName, str) {
    invisible(.Call('_mlpack_IO_SetParamVecString', PACKAGE = 'mlpack', paramName, str))
}

IO_SetParamVecInt <- function(paramName, ints) {
    invisible(.Call('_mlpack_IO_SetParamVecInt', PACKAGE = 'mlpack', paramName, ints))
}

IO_SetParamMat <- function(paramName, paramValue) {
    invisible(.Call('_mlpack_IO_SetParamMat', PACKAGE = 'mlpack', paramName, paramValue))
}

IO_SetParamUMat <- function(paramName, paramValue) {
    invisible(.Call('_mlpack_IO_SetParamUMat', PACKAGE = 'mlpack', paramName, paramValue))
}

IO_SetParamRow <- function(paramName, paramValue) {
    invisible(.Call('_mlpack_IO_SetParamRow', PACKAGE = 'mlpack', paramName, paramValue))
}

IO_SetParamURow <- function(paramName, paramValue) {
    invisible(.Call('_mlpack_IO_SetParamURow', PACKAGE = 'mlpack', paramName, paramValue))
}

IO_SetParamCol <- function(paramName, paramValue) {
    invisible(.Call('_mlpack_IO_SetParamCol', PACKAGE = 'mlpack', paramName, paramValue))
}

IO_SetParamUCol <- function(paramName, paramValue) {
    invisible(.Call('_mlpack_IO_SetParamUCol', PACKAGE = 'mlpack', paramName, paramValue))
}

IO_SetParamMatWithInfo <- function(paramName, dimensions, paramValue) {
    invisible(.Call('_mlpack_IO_SetParamMatWithInfo', PACKAGE = 'mlpack', paramName, dimensions, paramValue))
}

IO_GetParamInt <- function(paramName) {
    .Call('_mlpack_IO_GetParamInt', PACKAGE = 'mlpack', paramName)
}

IO_GetParamDouble <- function(paramName) {
    .Call('_mlpack_IO_GetParamDouble', PACKAGE = 'mlpack', paramName)
}

IO_GetParamString <- function(paramName) {
    .Call('_mlpack_IO_GetParamString', PACKAGE = 'mlpack', paramName)
}

IO_GetParamBool <- function(paramName) {
    .Call('_mlpack_IO_GetParamBool', PACKAGE = 'mlpack', paramName)
}

IO_GetParamVecString <- function(paramName) {
    .Call('_mlpack_IO_GetParamVecString', PACKAGE = 'mlpack', paramName)
}

IO_GetParamVecInt <- function(paramName) {
    .Call('_mlpack_IO_GetParamVecInt', PACKAGE = 'mlpack', paramName)
}

IO_GetParamMat <- function(paramName) {
    .Call('_mlpack_IO_GetParamMat', PACKAGE = 'mlpack', paramName)
}

IO_GetParamUMat <- function(paramName) {
    .Call('_mlpack_IO_GetParamUMat', PACKAGE = 'mlpack', paramName)
}

IO_GetParamRow <- function(paramName) {
    .Call('_mlpack_IO_GetParamRow', PACKAGE = 'mlpack', paramName)
}

IO_GetParamURow <- function(paramName) {
    .Call('_mlpack_IO_GetParamURow', PACKAGE = 'mlpack', paramName)
}

IO_GetParamCol <- function(paramName) {
    .Call('_mlpack_IO_GetParamCol', PACKAGE = 'mlpack', paramName)
}

IO_GetParamUCol <- function(paramName) {
    .Call('_mlpack_IO_GetParamUCol', PACKAGE = 'mlpack', paramName)
}

IO_GetParamMatWithInfo <- function(paramName) {
    .Call('_mlpack_IO_GetParamMatWithInfo', PACKAGE = 'mlpack', paramName)
}

IO_EnableVerbose <- function() {
    invisible(.Call('_mlpack_IO_EnableVerbose', PACKAGE = 'mlpack'))
}

IO_DisableVerbose <- function() {
    invisible(.Call('_mlpack_IO_DisableVerbose', PACKAGE = 'mlpack'))
}

IO_ResetTimers <- function() {
    invisible(.Call('_mlpack_IO_ResetTimers', PACKAGE = 'mlpack'))
}

IO_SetPassed <- function(paramName) {
    invisible(.Call('_mlpack_IO_SetPassed', PACKAGE = 'mlpack', paramName))
}

IO_ClearSettings <- function() {
    invisible(.Call('_mlpack_IO_ClearSettings', PACKAGE = 'mlpack'))
}

radical_mlpackMain <- function() {
    invisible(.Call('_mlpack_radical_mlpackMain', PACKAGE = 'mlpack'))
}

random_forest_mlpackMain <- function() {
    invisible(.Call('_mlpack_random_forest_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamRandomForestModelPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamRandomForestModelPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamRandomForestModelPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamRandomForestModelPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeRandomForestModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeRandomForestModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeRandomForestModelPtr <- function(str) {
    .Call('_mlpack_DeserializeRandomForestModelPtr', PACKAGE = 'mlpack', str)
}

range_search_mlpackMain <- function() {
    invisible(.Call('_mlpack_range_search_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamRSModelPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamRSModelPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamRSModelPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamRSModelPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeRSModelPtr <- function(ptr) {
    .Call('_mlpack_SerializeRSModelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeRSModelPtr <- function(str) {
    .Call('_mlpack_DeserializeRSModelPtr', PACKAGE = 'mlpack', str)
}

softmax_regression_mlpackMain <- function() {
    invisible(.Call('_mlpack_softmax_regression_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamSoftmaxRegressionPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamSoftmaxRegressionPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamSoftmaxRegressionPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamSoftmaxRegressionPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeSoftmaxRegressionPtr <- function(ptr) {
    .Call('_mlpack_SerializeSoftmaxRegressionPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeSoftmaxRegressionPtr <- function(str) {
    .Call('_mlpack_DeserializeSoftmaxRegressionPtr', PACKAGE = 'mlpack', str)
}

sparse_coding_mlpackMain <- function() {
    invisible(.Call('_mlpack_sparse_coding_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamSparseCodingPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamSparseCodingPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamSparseCodingPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamSparseCodingPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeSparseCodingPtr <- function(ptr) {
    .Call('_mlpack_SerializeSparseCodingPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeSparseCodingPtr <- function(str) {
    .Call('_mlpack_DeserializeSparseCodingPtr', PACKAGE = 'mlpack', str)
}

test_r_binding_mlpackMain <- function() {
    invisible(.Call('_mlpack_test_r_binding_mlpackMain', PACKAGE = 'mlpack'))
}

IO_GetParamGaussianKernelPtr <- function(paramName) {
    .Call('_mlpack_IO_GetParamGaussianKernelPtr', PACKAGE = 'mlpack', paramName)
}

IO_SetParamGaussianKernelPtr <- function(paramName, ptr) {
    invisible(.Call('_mlpack_IO_SetParamGaussianKernelPtr', PACKAGE = 'mlpack', paramName, ptr))
}

SerializeGaussianKernelPtr <- function(ptr) {
    .Call('_mlpack_SerializeGaussianKernelPtr', PACKAGE = 'mlpack', ptr)
}

DeserializeGaussianKernelPtr <- function(str) {
    .Call('_mlpack_DeserializeGaussianKernelPtr', PACKAGE = 'mlpack', str)
}

