# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lars_mlpackMain <- function() {
    invisible(.Call(`_RcppMLPACK_lars_mlpackMain`))
}

CLI_GetParamLARSPtr <- function(paramName) {
    .Call(`_RcppMLPACK_CLI_GetParamLARSPtr`, paramName)
}

CLI_SetParamLARSPtr <- function(paramName, ptr) {
    invisible(.Call(`_RcppMLPACK_CLI_SetParamLARSPtr`, paramName, ptr))
}

SerializeLARSToXML <- function(ptr) {
    .Call(`_RcppMLPACK_SerializeLARSToXML`, ptr)
}

SerializeLARSPtr <- function(ptr) {
    .Call(`_RcppMLPACK_SerializeLARSPtr`, ptr)
}

UnserializeLARSPtr <- function(str) {
    .Call(`_RcppMLPACK_UnserializeLARSPtr`, str)
}

pca_mlpackMain <- function() {
    invisible(.Call(`_RcppMLPACK_pca_mlpackMain`))
}

CLI_RestoreSettings <- function(programName) {
    invisible(.Call(`_RcppMLPACK_CLI_RestoreSettings`, programName))
}

CLI_SetParamInt <- function(paramName, paramValue) {
    invisible(.Call(`_RcppMLPACK_CLI_SetParamInt`, paramName, paramValue))
}

CLI_SetParamDouble <- function(paramName, paramValue) {
    invisible(.Call(`_RcppMLPACK_CLI_SetParamDouble`, paramName, paramValue))
}

CLI_SetParamString <- function(paramName, paramValue) {
    invisible(.Call(`_RcppMLPACK_CLI_SetParamString`, paramName, paramValue))
}

CLI_SetParamBool <- function(paramName, paramValue) {
    invisible(.Call(`_RcppMLPACK_CLI_SetParamBool`, paramName, paramValue))
}

CLI_SetParamVectorStr <- function(paramName, str) {
    invisible(.Call(`_RcppMLPACK_CLI_SetParamVectorStr`, paramName, str))
}

CLI_SetParamVectorInt <- function(paramName, ints) {
    invisible(.Call(`_RcppMLPACK_CLI_SetParamVectorInt`, paramName, ints))
}

CLI_SetParamMat <- function(paramName, paramValue) {
    invisible(.Call(`_RcppMLPACK_CLI_SetParamMat`, paramName, paramValue))
}

CLI_SetParamUMat <- function(paramName, paramValue) {
    invisible(.Call(`_RcppMLPACK_CLI_SetParamUMat`, paramName, paramValue))
}

CLI_SetParamRow <- function(paramName, paramValue) {
    invisible(.Call(`_RcppMLPACK_CLI_SetParamRow`, paramName, paramValue))
}

CLI_SetParamURow <- function(paramName, paramValue) {
    invisible(.Call(`_RcppMLPACK_CLI_SetParamURow`, paramName, paramValue))
}

CLI_SetParamCol <- function(paramName, paramValue) {
    invisible(.Call(`_RcppMLPACK_CLI_SetParamCol`, paramName, paramValue))
}

CLI_SetParamUCol <- function(paramName, paramValue) {
    invisible(.Call(`_RcppMLPACK_CLI_SetParamUCol`, paramName, paramValue))
}

CLI_SetParamMatWithInfo <- function(paramName, dimensions, paramValue) {
    invisible(.Call(`_RcppMLPACK_CLI_SetParamMatWithInfo`, paramName, dimensions, paramValue))
}

CLI_GetParamInt <- function(paramName) {
    .Call(`_RcppMLPACK_CLI_GetParamInt`, paramName)
}

CLI_GetParamDouble <- function(paramName) {
    .Call(`_RcppMLPACK_CLI_GetParamDouble`, paramName)
}

CLI_GetParamString <- function(paramName) {
    .Call(`_RcppMLPACK_CLI_GetParamString`, paramName)
}

CLI_GetParamBool <- function(paramName) {
    .Call(`_RcppMLPACK_CLI_GetParamBool`, paramName)
}

CLI_GetParamVectorStr <- function(paramName) {
    .Call(`_RcppMLPACK_CLI_GetParamVectorStr`, paramName)
}

CLI_GetParamVectorInt <- function(paramName) {
    .Call(`_RcppMLPACK_CLI_GetParamVectorInt`, paramName)
}

CLI_GetParamMat <- function(paramName) {
    .Call(`_RcppMLPACK_CLI_GetParamMat`, paramName)
}

CLI_GetParamUMat <- function(paramName) {
    .Call(`_RcppMLPACK_CLI_GetParamUMat`, paramName)
}

CLI_GetParamRow <- function(paramName) {
    .Call(`_RcppMLPACK_CLI_GetParamRow`, paramName)
}

CLI_GetParamURow <- function(paramName) {
    .Call(`_RcppMLPACK_CLI_GetParamURow`, paramName)
}

CLI_GetParamCol <- function(paramName) {
    .Call(`_RcppMLPACK_CLI_GetParamCol`, paramName)
}

CLI_GetParamUCol <- function(paramName) {
    .Call(`_RcppMLPACK_CLI_GetParamUCol`, paramName)
}

CLI_GetParamMatWithInfo <- function(paramName) {
    .Call(`_RcppMLPACK_CLI_GetParamMatWithInfo`, paramName)
}

CLI_EnableVerbose <- function() {
    invisible(.Call(`_RcppMLPACK_CLI_EnableVerbose`))
}

CLI_DisableVerbose <- function() {
    invisible(.Call(`_RcppMLPACK_CLI_DisableVerbose`))
}

CLI_ResetTimers <- function() {
    invisible(.Call(`_RcppMLPACK_CLI_ResetTimers`))
}

CLI_SetPassed <- function(paramName) {
    invisible(.Call(`_RcppMLPACK_CLI_SetPassed`, paramName))
}

CLI_ClearSettings <- function() {
    invisible(.Call(`_RcppMLPACK_CLI_ClearSettings`))
}

test_r_binding_mlpackMain <- function() {
    invisible(.Call(`_RcppMLPACK_test_r_binding_mlpackMain`))
}

CLI_GetParamGaussianKernelPtr <- function(paramName) {
    .Call(`_RcppMLPACK_CLI_GetParamGaussianKernelPtr`, paramName)
}

CLI_SetParamGaussianKernelPtr <- function(paramName, ptr) {
    invisible(.Call(`_RcppMLPACK_CLI_SetParamGaussianKernelPtr`, paramName, ptr))
}

SerializeGaussianKernelToXML <- function(ptr) {
    .Call(`_RcppMLPACK_SerializeGaussianKernelToXML`, ptr)
}

SerializeGaussianKernelPtr <- function(ptr) {
    .Call(`_RcppMLPACK_SerializeGaussianKernelPtr`, ptr)
}

UnserializeGaussianKernelPtr <- function(str) {
    .Call(`_RcppMLPACK_UnserializeGaussianKernelPtr`, str)
}

